# Generated by Django 4.1.7 on 2023-03-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='groupNickname',
            new_name='specialization',
        ),
    ]
