# Generated by Django 4.1.7 on 2023-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_colour',
            field=models.CharField(default='blue', max_length=200),
        ),
    ]
