# Generated by Django 4.1.7 on 2023-03-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_favoritenumber_student_cnp_alter_class_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('CNP',)},
        ),
    ]
