# Generated by Django 4.1.7 on 2023-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_groupnickname_group_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='favoriteNumber',
            new_name='CNP',
        ),
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='lesson_type',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Sem', 'Sem'), ('Course', 'Course')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
