# Generated by Django 4.1.7 on 2023-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('group', models.IntegerField(default=921)),
                ('age', models.IntegerField(default=18)),
                ('favorite_subject', models.CharField(max_length=200)),
            ],
        ),
    ]
