# Generated by Django 4.1.7 on 2023-03-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student_favorite_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_subject',
        ),
    ]
